spring.application.name=prw3_2026_1_api

# Configuração do banco de dados H2 (gravado em arquivo dentro do projeto)
spring.datasource.url=jdbc:h2:file:./DATA/prw3api
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra no log os comandos SQL que o Hibernate executa (formatados)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
